version: "3"
services:
  app:
    build: .
    depends_on: 
      - postgres
    ports:
      - "2000:2000"

  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=ssb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
