version: "3"
services:
  app:
    build: .
    networks:
      front:
        ipv4_address: 192.168.241.51
    container_name: ssb-app
    ports:
      - "2000:2000"

networks:
  front:
    # use the bridge driver, but enable IPv4
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv4: "true"
    ipam:
      driver: default
      config:
        - subnet: 192.168.241.0/24
